name: hydrasim2
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python>=3.12.4
  - nextflow>=24.04.3
  - badread>=0.4.1
  - ncbi-datasets-cli>=16.24.1
  - rasusa>=2.0.0
  - sra-tools>=3.1.1
  - pip>=24.0
